### ISSUE TITLE
Invalid JSON payload received

### ISSUE THREAD

**Issue by JuniYadi** [rapidwebltd/php-google-people-api#25]
Look like Google People Need Updates

```
PHP Fatal error:  Uncaught Exception: {
  "error": {
    "code": 400,
    "message": "Invalid JSON payload received. Unknown name \"parent\": Cannot bind query parameter. Field 'parent' could not be found in request message.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "description": "Invalid JSON payload received. Unknown name \"parent\": Cannot bind query parameter. Field 'parent' could not be found in request message."
          }
        ]
      }
    ]
  }
}
 in /var/www/html/php-google-people/vendor/rapidwebltd/php-google-people-api/src/GooglePeople.php:132
Stack trace:
#0 /var/www/html/php-google-people/vendor/rapidwebltd/php-google-people-api/src/Contact.php(16): RapidWeb\GooglePeopleAPI\GooglePeople->save(Object(RapidWeb\GooglePeopleAPI\Contact))
#1 /var/www/html/php-google-people/save.php(18): RapidWeb\GooglePeopleAPI\Contact->save()
#2 {main}
  thrown in /var/www/html/php-google-people/vendor/rapidwebltd/php-google-people-api/src/GooglePeople.php on line 132
```

**Comment by dvdwalker** [comment]
@JuniYadi your fix worked like a charm. Saved my day. Thanks!

**Comment by JuniYadi** [comment]
> @JuniYadi your fix worked like a charm. Saved my day. Thanks!

You're welcome, enjoy..

**Comment by hans77cz** [comment]
Same issue here. 

@JuniYadi fix worked. Thanks!

Waiting for PR approval :)

**Comment by Jord-JD** [comment]
PR merged. Will release shortly.
