### ISSUE TITLE
Setup.php PHP Fatal error:  Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by jperez-idoneo** [rapidwebltd/php-google-people-api#42]
Executing the setup.php when i obtain the auth code, once i paste in the shell, it returns me the following error:

PHP Fatal error:  Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in C:\Users\renti\Desktop\API-GOOGLE\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:201
Stack trace:
#0 C:\Users\renti\Desktop\API-GOOGLE\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection()
#1 C:\Users\renti\Desktop\API-GOOGLE\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError()
#2 C:\Users\renti\Desktop\API-GOOGLE\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish()
#3 C:\Users\renti\Desktop\API-GOOGLE\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke()
#4 C:\Users\renti\Desktop\API-GOOGLE\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}()
#5 C:\Users\renti\Desktop\API-GOOGLE\vendor\guzzlehttp\guzzle\src\PrepareBodyMiddleware.php(66): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}()
#6 C:\Users\renti\Desktop\API-GOOGLE\vendor\guzzlehttp\guzzle\src\Middleware.php(29): GuzzleHttp\PrepareBodyMiddleware->__invoke()
#7 C:\Users\renti\Desktop\API-GOOGLE\vendor\guzzlehttp\guzzle\src\RedirectMiddleware.php(70): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#8 C:\Users\renti\Desktop\API-GOOGLE\vendor\guzzlehttp\guzzle\src\Middleware.php(57): GuzzleHttp\RedirectMiddleware->__invoke()
#9 C:\Users\renti\Desktop\API-GOOGLE\vendor\guzzlehttp\guzzle\src\HandlerStack.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#10 C:\Users\renti\Desktop\API-GOOGLE\vendor\guzzlehttp\guzzle\src\Client.php(351): GuzzleHttp\HandlerStack->__invoke()
#11 C:\Users\renti\Desktop\API-GOOGLE\vendor\guzzlehttp\guzzle\src\Client.php(112): GuzzleHttp\Client->transfer()
#12 C:\Users\renti\Desktop\API-GOOGLE\vendor\guzzlehttp\guzzle\src\Client.php(129): GuzzleHttp\Client->sendAsync()
#13 C:\Users\renti\Desktop\API-GOOGLE\vendor\google\auth\src\HttpHandler\Guzzle6HttpHandler.php(47): GuzzleHttp\Client->send()
#14 C:\Users\renti\Desktop\API-GOOGLE\vendor\google\auth\src\OAuth2.php(535): Google\Auth\HttpHandler\Guzzle6HttpHandler->__invoke()
#15 C:\Users\renti\Desktop\API-GOOGLE\vendor\google\apiclient\src\Client.php(247): Google\Auth\OAuth2->fetchAuthToken()
#16 C:\Users\renti\Desktop\API-GOOGLE\vendor\google\apiclient\src\Client.php(226): Google\Client->fetchAccessTokenWithAuthCode()
#17 C:\Users\renti\Desktop\API-GOOGLE\vendor\rapidwebltd\php-google-oauth-2-handler\src\GoogleOAuth2Handler.php(50): Google\Client->authenticate()
#18 C:\Users\renti\Desktop\API-GOOGLE\vendor\rapidwebltd\php-google-oauth-2-handler\src\setup.php(65): RapidWeb\GoogleOAuth2Handler\GoogleOAuth2Handler->getRefreshToken()
#19 {main}
  thrown in C:\Users\renti\Desktop\API-GOOGLE\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 201

Notes: My account is set as TV and limited entry, and im in testing, not production, but i have set a testing account.

Thanks in advance

**Comment by jperez-idoneo** [comment]
It was PHP.ini config in ssl ^^
